#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimBP_Fish

#include "Basic.hpp"

#include "AnimBP_Fish_classes.hpp"
#include "AnimBP_Fish_parameters.hpp"


namespace SDK
{

// Function AnimBP_Fish.AnimBP_Fish_C.ExecuteUbergraph_AnimBP_Fish
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAnimBP_Fish_C::ExecuteUbergraph_AnimBP_Fish(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_Fish_C", "ExecuteUbergraph_AnimBP_Fish");

	Params::AnimBP_Fish_C_ExecuteUbergraph_AnimBP_Fish Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AnimBP_Fish.AnimBP_Fish_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UAnimBP_Fish_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_Fish_C", "AnimGraph");

	Params::AnimBP_Fish_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}

}

