#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BacktraceBlueprintLibrary

#include "Basic.hpp"

#include "BacktraceBlueprintLibrary_classes.hpp"


namespace SDK
{

// Function BacktraceBlueprintLibrary.BacktraceBlueprintLibrary.Crash
// (Final, Native, Static, Public, BlueprintCallable)

void UBacktraceBlueprintLibrary::Crash()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BacktraceBlueprintLibrary", "Crash");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}

}

