#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DroppedItem_Toy

#include "Basic.hpp"

#include "BP_DroppedItem_Toy_classes.hpp"
#include "BP_DroppedItem_Toy_parameters.hpp"


namespace SDK
{

// Function BP_DroppedItem_Toy.BP_DroppedItem_Toy_C.ExecuteUbergraph_BP_DroppedItem_Toy
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DroppedItem_Toy_C::ExecuteUbergraph_BP_DroppedItem_Toy(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DroppedItem_Toy_C", "ExecuteUbergraph_BP_DroppedItem_Toy");

	Params::BP_DroppedItem_Toy_C_ExecuteUbergraph_BP_DroppedItem_Toy Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DroppedItem_Toy.BP_DroppedItem_Toy_C.GlowEyes
// (BlueprintCallable, BlueprintEvent)

void ABP_DroppedItem_Toy_C::GlowEyes()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DroppedItem_Toy_C", "GlowEyes");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DroppedItem_Toy.BP_DroppedItem_Toy_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_DroppedItem_Toy_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DroppedItem_Toy_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DroppedItem_Toy.BP_DroppedItem_Toy_C.BndEvt__BP_DroppedItem_Toy_ItemMesh_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              HitComponent                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   NormalImpulse                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                Hit                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_DroppedItem_Toy_C::BndEvt__BP_DroppedItem_Toy_ItemMesh_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature(class UPrimitiveComponent* HitComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, const struct FVector& NormalImpulse, const struct FHitResult& Hit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DroppedItem_Toy_C", "BndEvt__BP_DroppedItem_Toy_ItemMesh_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature");

	Params::BP_DroppedItem_Toy_C_BndEvt__BP_DroppedItem_Toy_ItemMesh_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature Parms{};

	Parms.HitComponent = HitComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.NormalImpulse = std::move(NormalImpulse);
	Parms.Hit = std::move(Hit);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DroppedItem_Toy.BP_DroppedItem_Toy_C.Glow__UpdateFunc
// (BlueprintEvent)

void ABP_DroppedItem_Toy_C::Glow__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DroppedItem_Toy_C", "Glow__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DroppedItem_Toy.BP_DroppedItem_Toy_C.Glow__FinishedFunc
// (BlueprintEvent)

void ABP_DroppedItem_Toy_C::Glow__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DroppedItem_Toy_C", "Glow__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DroppedItem_Toy.BP_DroppedItem_Toy_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_DroppedItem_Toy_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DroppedItem_Toy_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

