#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DroppedItem_AlmondWater

#include "Basic.hpp"

#include "BP_DroppedItem_AlmondWater_classes.hpp"
#include "BP_DroppedItem_AlmondWater_parameters.hpp"


namespace SDK
{

// Function BP_DroppedItem_AlmondWater.BP_DroppedItem_AlmondWater_C.ExecuteUbergraph_BP_DroppedItem_AlmondWater
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DroppedItem_AlmondWater_C::ExecuteUbergraph_BP_DroppedItem_AlmondWater(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DroppedItem_AlmondWater_C", "ExecuteUbergraph_BP_DroppedItem_AlmondWater");

	Params::BP_DroppedItem_AlmondWater_C_ExecuteUbergraph_BP_DroppedItem_AlmondWater Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DroppedItem_AlmondWater.BP_DroppedItem_AlmondWater_C.ToggleEvent
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Enable                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_DroppedItem_AlmondWater_C::ToggleEvent(bool Enable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DroppedItem_AlmondWater_C", "ToggleEvent");

	Params::BP_DroppedItem_AlmondWater_C_ToggleEvent Parms{};

	Parms.Enable = Enable;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DroppedItem_AlmondWater.BP_DroppedItem_AlmondWater_C.OnEventLoaded
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EEventType                              EventType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DroppedItem_AlmondWater_C::OnEventLoaded(EEventType EventType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DroppedItem_AlmondWater_C", "OnEventLoaded");

	Params::BP_DroppedItem_AlmondWater_C_OnEventLoaded Parms{};

	Parms.EventType = EventType;

	UObject::ProcessEvent(Func, &Parms);
}

}

