#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DroppedItem_Knife

#include "Basic.hpp"

#include "BP_DroppedItem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DroppedItem_Knife.BP_DroppedItem_Knife_C
// 0x0008 (0x0278 - 0x0270)
class ABP_DroppedItem_Knife_C final : public ABP_DroppedItem_C
{
public:
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x0270(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_DroppedItem_Knife_C">();
	}
	static class ABP_DroppedItem_Knife_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DroppedItem_Knife_C>();
	}
};
static_assert(alignof(ABP_DroppedItem_Knife_C) == 0x000008, "Wrong alignment on ABP_DroppedItem_Knife_C");
static_assert(sizeof(ABP_DroppedItem_Knife_C) == 0x000278, "Wrong size on ABP_DroppedItem_Knife_C");
static_assert(offsetof(ABP_DroppedItem_Knife_C, StaticMesh) == 0x000270, "Member 'ABP_DroppedItem_Knife_C::StaticMesh' has a wrong offset!");

}

