#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Firework_Shake

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Firework_Shake.BP_Firework_Shake_C
// 0x0000 (0x01B0 - 0x01B0)
class UBP_Firework_Shake_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Firework_Shake_C">();
	}
	static class UBP_Firework_Shake_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Firework_Shake_C>();
	}
};
static_assert(alignof(UBP_Firework_Shake_C) == 0x000010, "Wrong alignment on UBP_Firework_Shake_C");
static_assert(sizeof(UBP_Firework_Shake_C) == 0x0001B0, "Wrong size on UBP_Firework_Shake_C");

}

