#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_KnifeInHand

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_KnifeInHand.BP_KnifeInHand_C
// 0x0010 (0x0230 - 0x0220)
class ABP_KnifeInHand_C final : public AActor
{
public:
	class UStaticMeshComponent*                   Mesh;                                              // 0x0220(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_KnifeInHand_C">();
	}
	static class ABP_KnifeInHand_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_KnifeInHand_C>();
	}
};
static_assert(alignof(ABP_KnifeInHand_C) == 0x000008, "Wrong alignment on ABP_KnifeInHand_C");
static_assert(sizeof(ABP_KnifeInHand_C) == 0x000230, "Wrong size on ABP_KnifeInHand_C");
static_assert(offsetof(ABP_KnifeInHand_C, Mesh) == 0x000220, "Member 'ABP_KnifeInHand_C::Mesh' has a wrong offset!");
static_assert(offsetof(ABP_KnifeInHand_C, DefaultSceneRoot) == 0x000228, "Member 'ABP_KnifeInHand_C::DefaultSceneRoot' has a wrong offset!");

}

