#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RowBoat

#include "Basic.hpp"

#include "AIModule_structs.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Backrooms_classes.hpp"
#include "E_CameraSetting_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_RowBoat.BP_RowBoat_C
// 0x0100 (0x0420 - 0x0320)
class ABP_RowBoat_C final : public ABoatPawn
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0320(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBoxComponent*                          Collision3;                                        // 0x0328(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          Collision2;                                        // 0x0330(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          Collision1;                                        // 0x0338(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          Collision;                                         // 0x0340(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          Collision4;                                        // 0x0348(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh5;                                       // 0x0350(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh4;                                       // 0x0358(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 SkeletalMesh1;                                     // 0x0360(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh3;                                       // 0x0368(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh2;                                       // 0x0370(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 SkeletalMesh;                                      // 0x0378(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         Bob_Buoyancy_BBCAF16E44F03C8EA7F96D944744C90E;     // 0x0380(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Bob__Direction_BBCAF16E44F03C8EA7F96D944744C90E;   // 0x0384(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_385[0x3];                                      // 0x0385(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Bob;                                               // 0x0388(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_2_Alpha_F29818AD45D576B700E4C888ABCA1273; // 0x0390(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Timeline_2__Direction_F29818AD45D576B700E4C888ABCA1273; // 0x0394(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_395[0x3];                                      // 0x0395(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Timeline_2;                                        // 0x0398(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Timeline_1__Direction_A8B0AB574F32E48C188E48BD0302DAFF; // 0x03A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3A1[0x7];                                      // 0x03A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Timeline_1;                                        // 0x03A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_0_X_72EF829B4333A04EF68203BDFCAE61CC;     // 0x03B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Timeline_0__Direction_72EF829B4333A04EF68203BDFCAE61CC; // 0x03B4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3B5[0x3];                                      // 0x03B5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Timeline_0;                                        // 0x03B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsVisible;                                         // 0x03C0(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor)
	uint8                                         Pad_3C1[0x7];                                      // 0x03C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABPCharacter_Demo_C*                    Player;                                            // 0x03C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         LookAtActorSequenceCounter;                        // 0x03D0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               PlayerCurrentRotation;                             // 0x03D4(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          Looking;                                           // 0x03E0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          CanMove;                                           // 0x03E1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3E2[0x2];                                      // 0x03E2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Offset;                                            // 0x03E4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         BoatSwayMultiplier;                                // 0x03E8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CameraSwayMultiplier;                              // 0x03EC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AEight_FFT_H_Ocean_Sim_C*               Ocean;                                             // 0x03F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                LastWaterZ;                                        // 0x03F8(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          DidPossess;                                        // 0x0404(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor)
	uint8                                         Pad_405[0x3];                                      // 0x0405(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                TeleportLoc;                                       // 0x0408(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Delta_Seconds;                                     // 0x0414(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         TurnRate;                                          // 0x0418(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         MouseSensitivity;                                  // 0x041C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_RowBoat(int32 EntryPoint);
	void ReceiveTick(float DeltaSeconds);
	void LookUp(float Value);
	void Turn(float Value);
	void InpAxisEvt_LookUpRate_K2Node_InputAxisEvent_9(float AxisValue);
	void InpAxisEvt_TurnRate_K2Node_InputAxisEvent_0(float AxisValue);
	void InpAxisEvt_VRMove_X_K2Node_InputAxisEvent_8(float AxisValue);
	void InpAxisEvt_VRMove_Y_K2Node_InputAxisEvent_7(float AxisValue);
	void InpAxisEvt_VRTurn_Y_K2Node_InputAxisEvent_6(float AxisValue);
	void InpAxisEvt_VRTurn_X_K2Node_InputAxisEvent_5(float AxisValue);
	void StopBuoyancy();
	void StartBuoyancy();
	void StartDelay();
	void ResetDelay();
	void OnQueryFinished(class UEnvQueryInstanceBlueprintWrapper* QueryInstance, EEnvQueryStatus QueryStatus);
	void FindLand();
	void ReceiveUnpossessed(class AController* OldController);
	void UnPossess();
	void ReceivePossessed(class AController* NewController);
	void OnPossess();
	void StartLookAt(const struct FRotator& StartRot, const struct FRotator& EndRot);
	void Lookat2(class USkeletalMeshComponent* Mesh);
	void PlayWarning();
	void StartSway();
	void PlayScare();
	void ReceiveBeginPlay();
	void InpAxisEvt_MoveRight_K2Node_InputAxisEvent_90(float AxisValue);
	void InpAxisEvt_MoveForward_K2Node_InputAxisEvent_79(float AxisValue);
	void InpAxisEvt_Turn_K2Node_InputAxisEvent_47(float AxisValue);
	void InpAxisEvt_LookUp_K2Node_InputAxisEvent_40(float AxisValue);
	void InpActEvt_Interact_K2Node_InputActionEvent_0(const struct FKey& Key);
	void Bob__UpdateFunc();
	void Bob__FinishedFunc();
	void Timeline_2__UpdateFunc();
	void Timeline_2__FinishedFunc();
	void Timeline_1__UpdateFunc();
	void Timeline_1__FinishedFunc();
	void Timeline_0__UpdateFunc();
	void Timeline_0__FinishedFunc();
	void OnRep_IsVisible();
	void SetInput(bool Enabled);
	float GetWaterWorldZ(const struct FVector2D& InLocation);
	float GetWaterWorldZ_0(const struct FVector2D& InLocation);
	void OnRep_DidPossess();
	void UpdateWaterLevel();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_RowBoat_C">();
	}
	static class ABP_RowBoat_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_RowBoat_C>();
	}
};
static_assert(alignof(ABP_RowBoat_C) == 0x000008, "Wrong alignment on ABP_RowBoat_C");
static_assert(sizeof(ABP_RowBoat_C) == 0x000420, "Wrong size on ABP_RowBoat_C");
static_assert(offsetof(ABP_RowBoat_C, UberGraphFrame) == 0x000320, "Member 'ABP_RowBoat_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, Collision3) == 0x000328, "Member 'ABP_RowBoat_C::Collision3' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, Collision2) == 0x000330, "Member 'ABP_RowBoat_C::Collision2' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, Collision1) == 0x000338, "Member 'ABP_RowBoat_C::Collision1' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, Collision) == 0x000340, "Member 'ABP_RowBoat_C::Collision' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, Collision4) == 0x000348, "Member 'ABP_RowBoat_C::Collision4' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, StaticMesh5) == 0x000350, "Member 'ABP_RowBoat_C::StaticMesh5' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, StaticMesh4) == 0x000358, "Member 'ABP_RowBoat_C::StaticMesh4' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, SkeletalMesh1) == 0x000360, "Member 'ABP_RowBoat_C::SkeletalMesh1' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, StaticMesh3) == 0x000368, "Member 'ABP_RowBoat_C::StaticMesh3' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, StaticMesh2) == 0x000370, "Member 'ABP_RowBoat_C::StaticMesh2' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, SkeletalMesh) == 0x000378, "Member 'ABP_RowBoat_C::SkeletalMesh' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, Bob_Buoyancy_BBCAF16E44F03C8EA7F96D944744C90E) == 0x000380, "Member 'ABP_RowBoat_C::Bob_Buoyancy_BBCAF16E44F03C8EA7F96D944744C90E' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, Bob__Direction_BBCAF16E44F03C8EA7F96D944744C90E) == 0x000384, "Member 'ABP_RowBoat_C::Bob__Direction_BBCAF16E44F03C8EA7F96D944744C90E' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, Bob) == 0x000388, "Member 'ABP_RowBoat_C::Bob' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, Timeline_2_Alpha_F29818AD45D576B700E4C888ABCA1273) == 0x000390, "Member 'ABP_RowBoat_C::Timeline_2_Alpha_F29818AD45D576B700E4C888ABCA1273' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, Timeline_2__Direction_F29818AD45D576B700E4C888ABCA1273) == 0x000394, "Member 'ABP_RowBoat_C::Timeline_2__Direction_F29818AD45D576B700E4C888ABCA1273' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, Timeline_2) == 0x000398, "Member 'ABP_RowBoat_C::Timeline_2' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, Timeline_1__Direction_A8B0AB574F32E48C188E48BD0302DAFF) == 0x0003A0, "Member 'ABP_RowBoat_C::Timeline_1__Direction_A8B0AB574F32E48C188E48BD0302DAFF' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, Timeline_1) == 0x0003A8, "Member 'ABP_RowBoat_C::Timeline_1' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, Timeline_0_X_72EF829B4333A04EF68203BDFCAE61CC) == 0x0003B0, "Member 'ABP_RowBoat_C::Timeline_0_X_72EF829B4333A04EF68203BDFCAE61CC' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, Timeline_0__Direction_72EF829B4333A04EF68203BDFCAE61CC) == 0x0003B4, "Member 'ABP_RowBoat_C::Timeline_0__Direction_72EF829B4333A04EF68203BDFCAE61CC' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, Timeline_0) == 0x0003B8, "Member 'ABP_RowBoat_C::Timeline_0' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, IsVisible) == 0x0003C0, "Member 'ABP_RowBoat_C::IsVisible' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, Player) == 0x0003C8, "Member 'ABP_RowBoat_C::Player' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, LookAtActorSequenceCounter) == 0x0003D0, "Member 'ABP_RowBoat_C::LookAtActorSequenceCounter' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, PlayerCurrentRotation) == 0x0003D4, "Member 'ABP_RowBoat_C::PlayerCurrentRotation' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, Looking) == 0x0003E0, "Member 'ABP_RowBoat_C::Looking' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, CanMove) == 0x0003E1, "Member 'ABP_RowBoat_C::CanMove' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, Offset) == 0x0003E4, "Member 'ABP_RowBoat_C::Offset' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, BoatSwayMultiplier) == 0x0003E8, "Member 'ABP_RowBoat_C::BoatSwayMultiplier' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, CameraSwayMultiplier) == 0x0003EC, "Member 'ABP_RowBoat_C::CameraSwayMultiplier' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, Ocean) == 0x0003F0, "Member 'ABP_RowBoat_C::Ocean' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, LastWaterZ) == 0x0003F8, "Member 'ABP_RowBoat_C::LastWaterZ' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, DidPossess) == 0x000404, "Member 'ABP_RowBoat_C::DidPossess' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, TeleportLoc) == 0x000408, "Member 'ABP_RowBoat_C::TeleportLoc' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, Delta_Seconds) == 0x000414, "Member 'ABP_RowBoat_C::Delta_Seconds' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, TurnRate) == 0x000418, "Member 'ABP_RowBoat_C::TurnRate' has a wrong offset!");
static_assert(offsetof(ABP_RowBoat_C, MouseSensitivity) == 0x00041C, "Member 'ABP_RowBoat_C::MouseSensitivity' has a wrong offset!");

}

