#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SG_GameSettings

#include "Basic.hpp"

#include "E_CameraSetting_structs.hpp"
#include "S_AudioSettings_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SG_GameSettings.BP_SG_GameSettings_C
// 0x0040 (0x0068 - 0x0028)
class UBP_SG_GameSettings_C final : public USaveGame
{
public:
	struct FS_AudioSettings                       S_AudioSettings;                                   // 0x0028(0x001C)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         MouseSensitivity;                                  // 0x0044(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          InvertMouse;                                       // 0x0048(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          HasMotionBlur;                                     // 0x0049(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4A[0x2];                                       // 0x004A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         InputGain;                                         // 0x004C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_CameraSetting                               CameraSetting;                                     // 0x0050(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ShowBody;                                          // 0x0051(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          HasSeenVHS;                                        // 0x0052(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          UsingPushToTalk;                                   // 0x0053(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	int32                                         FOV;                                               // 0x0054(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          SmoothRotation;                                    // 0x0058(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          HideGore;                                          // 0x0059(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5A[0x2];                                       // 0x005A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Gamma;                                             // 0x005C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CameraShake;                                       // 0x0060(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          ShowEventContent;                                  // 0x0061(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          AimAssist;                                         // 0x0062(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          ControllerFeedback;                                // 0x0063(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          ShowChat;                                          // 0x0064(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_SG_GameSettings_C">();
	}
	static class UBP_SG_GameSettings_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SG_GameSettings_C>();
	}
};
static_assert(alignof(UBP_SG_GameSettings_C) == 0x000008, "Wrong alignment on UBP_SG_GameSettings_C");
static_assert(sizeof(UBP_SG_GameSettings_C) == 0x000068, "Wrong size on UBP_SG_GameSettings_C");
static_assert(offsetof(UBP_SG_GameSettings_C, S_AudioSettings) == 0x000028, "Member 'UBP_SG_GameSettings_C::S_AudioSettings' has a wrong offset!");
static_assert(offsetof(UBP_SG_GameSettings_C, MouseSensitivity) == 0x000044, "Member 'UBP_SG_GameSettings_C::MouseSensitivity' has a wrong offset!");
static_assert(offsetof(UBP_SG_GameSettings_C, InvertMouse) == 0x000048, "Member 'UBP_SG_GameSettings_C::InvertMouse' has a wrong offset!");
static_assert(offsetof(UBP_SG_GameSettings_C, HasMotionBlur) == 0x000049, "Member 'UBP_SG_GameSettings_C::HasMotionBlur' has a wrong offset!");
static_assert(offsetof(UBP_SG_GameSettings_C, InputGain) == 0x00004C, "Member 'UBP_SG_GameSettings_C::InputGain' has a wrong offset!");
static_assert(offsetof(UBP_SG_GameSettings_C, CameraSetting) == 0x000050, "Member 'UBP_SG_GameSettings_C::CameraSetting' has a wrong offset!");
static_assert(offsetof(UBP_SG_GameSettings_C, ShowBody) == 0x000051, "Member 'UBP_SG_GameSettings_C::ShowBody' has a wrong offset!");
static_assert(offsetof(UBP_SG_GameSettings_C, HasSeenVHS) == 0x000052, "Member 'UBP_SG_GameSettings_C::HasSeenVHS' has a wrong offset!");
static_assert(offsetof(UBP_SG_GameSettings_C, UsingPushToTalk) == 0x000053, "Member 'UBP_SG_GameSettings_C::UsingPushToTalk' has a wrong offset!");
static_assert(offsetof(UBP_SG_GameSettings_C, FOV) == 0x000054, "Member 'UBP_SG_GameSettings_C::FOV' has a wrong offset!");
static_assert(offsetof(UBP_SG_GameSettings_C, SmoothRotation) == 0x000058, "Member 'UBP_SG_GameSettings_C::SmoothRotation' has a wrong offset!");
static_assert(offsetof(UBP_SG_GameSettings_C, HideGore) == 0x000059, "Member 'UBP_SG_GameSettings_C::HideGore' has a wrong offset!");
static_assert(offsetof(UBP_SG_GameSettings_C, Gamma) == 0x00005C, "Member 'UBP_SG_GameSettings_C::Gamma' has a wrong offset!");
static_assert(offsetof(UBP_SG_GameSettings_C, CameraShake) == 0x000060, "Member 'UBP_SG_GameSettings_C::CameraShake' has a wrong offset!");
static_assert(offsetof(UBP_SG_GameSettings_C, ShowEventContent) == 0x000061, "Member 'UBP_SG_GameSettings_C::ShowEventContent' has a wrong offset!");
static_assert(offsetof(UBP_SG_GameSettings_C, AimAssist) == 0x000062, "Member 'UBP_SG_GameSettings_C::AimAssist' has a wrong offset!");
static_assert(offsetof(UBP_SG_GameSettings_C, ControllerFeedback) == 0x000063, "Member 'UBP_SG_GameSettings_C::ControllerFeedback' has a wrong offset!");
static_assert(offsetof(UBP_SG_GameSettings_C, ShowChat) == 0x000064, "Member 'UBP_SG_GameSettings_C::ShowChat' has a wrong offset!");

}

