#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Smiler_Zone

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Smiler_Zone.BP_Smiler_Zone_C
// 0x0010 (0x0238 - 0x0228)
class ABP_Smiler_Zone_C final : public ATriggerBox
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0228(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          IsLower;                                           // 0x0230(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_BP_Smiler_Zone(int32 EntryPoint);
	void BndEvt__BP_Smiler_Zone_CollisionComponent_K2Node_ComponentBoundEvent_3_ComponentEndOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex);
	void BndEvt__BP_NoClip_Zone_CollisionComponent_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Smiler_Zone_C">();
	}
	static class ABP_Smiler_Zone_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Smiler_Zone_C>();
	}
};
static_assert(alignof(ABP_Smiler_Zone_C) == 0x000008, "Wrong alignment on ABP_Smiler_Zone_C");
static_assert(sizeof(ABP_Smiler_Zone_C) == 0x000238, "Wrong size on ABP_Smiler_Zone_C");
static_assert(offsetof(ABP_Smiler_Zone_C, UberGraphFrame) == 0x000228, "Member 'ABP_Smiler_Zone_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_Smiler_Zone_C, IsLower) == 0x000230, "Member 'ABP_Smiler_Zone_C::IsLower' has a wrong offset!");

}

