#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPFL_ControllerSupport

#include "Basic.hpp"

#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function BPFL_ControllerSupport.BPFL_ControllerSupport_C.GetGridNavigationNextIndex
// 0x00B8 (0x00B8 - 0x0000)
struct BPFL_ControllerSupport_C_GetGridNavigationNextIndex final
{
public:
	int32                                         CurrentIndex;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ArrayLength;                                       // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Columns;                                           // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EUINavigation                                 Direction;                                         // 0x000C(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                __WorldContext;                                    // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         NewIndex;                                          // 0x0018(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         TempNewIndex;                                      // 0x001C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Divide_IntInt_ReturnValue;                // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_1;            // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_31[0x3];                                       // 0x0031(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Percent_IntInt_ReturnValue;               // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Percent_IntInt_ReturnValue_1;             // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_41[0x3];                                       // 0x0041(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_SelectInt_ReturnValue;                    // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_2;            // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_3;            // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_4;            // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_5;            // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_6;            // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Percent_IntInt_ReturnValue_2;             // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_7;            // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x006C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_6D[0x3];                                       // 0x006D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_8;            // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_SelectInt_ReturnValue_1;                  // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_2;                // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_79[0x3];                                       // 0x0079(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x007C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_SelectInt_ReturnValue_2;                  // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_9;            // 0x0084(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Multiply_IntInt_ReturnValue;              // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_4;                 // 0x008C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_10;           // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_3;                // 0x0094(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_95[0x3];                                       // 0x0095(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_SelectInt_ReturnValue_3;                  // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_SelectInt_ReturnValue_4;                  // 0x009C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Percent_IntInt_ReturnValue_3;             // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_11;           // 0x00A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue_1;        // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A9[0x3];                                       // 0x00A9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_SelectInt_ReturnValue_5;                  // 0x00AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_4;                // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_B1[0x3];                                       // 0x00B1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_SelectInt_ReturnValue_6;                  // 0x00B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex) == 0x000008, "Wrong alignment on BPFL_ControllerSupport_C_GetGridNavigationNextIndex");
static_assert(sizeof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex) == 0x0000B8, "Wrong size on BPFL_ControllerSupport_C_GetGridNavigationNextIndex");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CurrentIndex) == 0x000000, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CurrentIndex' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, ArrayLength) == 0x000004, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::ArrayLength' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, Columns) == 0x000008, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::Columns' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, Direction) == 0x00000C, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::Direction' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, __WorldContext) == 0x000010, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::__WorldContext' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, NewIndex) == 0x000018, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::NewIndex' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, TempNewIndex) == 0x00001C, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::TempNewIndex' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, K2Node_SwitchEnum_CmpSuccess) == 0x000020, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_Divide_IntInt_ReturnValue) == 0x000024, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_Divide_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_Subtract_IntInt_ReturnValue) == 0x000028, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_Subtract_IntInt_ReturnValue_1) == 0x00002C, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_Subtract_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_GreaterEqual_IntInt_ReturnValue) == 0x000030, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_GreaterEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_Percent_IntInt_ReturnValue) == 0x000034, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_Percent_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_Add_IntInt_ReturnValue) == 0x000038, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_Percent_IntInt_ReturnValue_1) == 0x00003C, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_Percent_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_Less_IntInt_ReturnValue) == 0x000040, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_SelectInt_ReturnValue) == 0x000044, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_SelectInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_Subtract_IntInt_ReturnValue_2) == 0x000048, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_Subtract_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_Subtract_IntInt_ReturnValue_3) == 0x00004C, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_Subtract_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_Subtract_IntInt_ReturnValue_4) == 0x000050, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_Subtract_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_Add_IntInt_ReturnValue_1) == 0x000054, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_Subtract_IntInt_ReturnValue_5) == 0x000058, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_Subtract_IntInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_Subtract_IntInt_ReturnValue_6) == 0x00005C, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_Subtract_IntInt_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_Percent_IntInt_ReturnValue_2) == 0x000060, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_Percent_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_Subtract_IntInt_ReturnValue_7) == 0x000064, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_Subtract_IntInt_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_Add_IntInt_ReturnValue_2) == 0x000068, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_Less_IntInt_ReturnValue_1) == 0x00006C, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_Subtract_IntInt_ReturnValue_8) == 0x000070, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_Subtract_IntInt_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_SelectInt_ReturnValue_1) == 0x000074, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_SelectInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_Less_IntInt_ReturnValue_2) == 0x000078, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_Less_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_Add_IntInt_ReturnValue_3) == 0x00007C, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_Add_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_SelectInt_ReturnValue_2) == 0x000080, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_SelectInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_Subtract_IntInt_ReturnValue_9) == 0x000084, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_Subtract_IntInt_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_Multiply_IntInt_ReturnValue) == 0x000088, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_Multiply_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_Add_IntInt_ReturnValue_4) == 0x00008C, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_Add_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_Subtract_IntInt_ReturnValue_10) == 0x000090, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_Subtract_IntInt_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_Less_IntInt_ReturnValue_3) == 0x000094, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_Less_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_SelectInt_ReturnValue_3) == 0x000098, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_SelectInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_SelectInt_ReturnValue_4) == 0x00009C, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_SelectInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_Percent_IntInt_ReturnValue_3) == 0x0000A0, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_Percent_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_Subtract_IntInt_ReturnValue_11) == 0x0000A4, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_Subtract_IntInt_ReturnValue_11' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_GreaterEqual_IntInt_ReturnValue_1) == 0x0000A8, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_GreaterEqual_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_SelectInt_ReturnValue_5) == 0x0000AC, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_SelectInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_Less_IntInt_ReturnValue_4) == 0x0000B0, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_Less_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BPFL_ControllerSupport_C_GetGridNavigationNextIndex, CallFunc_SelectInt_ReturnValue_6) == 0x0000B4, "Member 'BPFL_ControllerSupport_C_GetGridNavigationNextIndex::CallFunc_SelectInt_ReturnValue_6' has a wrong offset!");

}

