#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPFL_EntitySighting

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPFL_EntitySighting.BPFL_EntitySighting_C
// 0x0000 (0x0028 - 0x0028)
class UBPFL_EntitySighting_C final : public UBlueprintFunctionLibrary
{
public:
	static void CallOnEntitySighted_Controller(class AController* OwningController, class UObject* __WorldContext);
	static void CallOnEntitySighted_Actor(class AActor* OwningActor, class UObject* __WorldContext);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPFL_EntitySighting_C">();
	}
	static class UBPFL_EntitySighting_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPFL_EntitySighting_C>();
	}
};
static_assert(alignof(UBPFL_EntitySighting_C) == 0x000008, "Wrong alignment on UBPFL_EntitySighting_C");
static_assert(sizeof(UBPFL_EntitySighting_C) == 0x000028, "Wrong size on UBPFL_EntitySighting_C");

}

