#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ClimbLadderSequence

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "LevelSequence_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ClimbLadderSequence.SequenceDirector_C
// 0x0008 (0x0040 - 0x0038)
class ClimbLadderSequence::USequenceDirector_C final : public ULevelSequenceDirector
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0038(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_SequenceDirector(int32 EntryPoint);
	void SequenceEvent_0();
	void SequenceEvent__ENTRYPOINTSequenceDirector_0();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BlueprintGeneratedClass ClimbLadderSequence.SequenceDirector_C", true, "SequenceDirector_C">();
	}
	static class ClimbLadderSequence::USequenceDirector_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ClimbLadderSequence::USequenceDirector_C>();
	}
};
static_assert(alignof(ClimbLadderSequence::USequenceDirector_C) == 0x000008, "Wrong alignment on ClimbLadderSequence::USequenceDirector_C");
static_assert(sizeof(ClimbLadderSequence::USequenceDirector_C) == 0x000040, "Wrong size on ClimbLadderSequence::USequenceDirector_C");
static_assert(offsetof(ClimbLadderSequence::USequenceDirector_C, UberGraphFrame) == 0x000038, "Member 'ClimbLadderSequence::USequenceDirector_C::UberGraphFrame' has a wrong offset!");

}

