#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FluidDynamicForceMeshType

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum FluidDynamicForceMeshType.FluidDynamicForceMeshType
// NumValues: 0x0003
enum class EFluidDynamicForceMeshType : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	FluidDynamicForceMeshType_MAX            = 2,
};

}

