#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Grass2_Component_BP

#include "Basic.hpp"

#include "INTERACTIVE_FoliageComp_BP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Grass2_Component_BP.Grass2_Component_BP_C
// 0x0000 (0x0800 - 0x0800)
class UGrass2_Component_BP_C final : public UINTERACTIVE_FoliageComp_BP_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Grass2_Component_BP_C">();
	}
	static class UGrass2_Component_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGrass2_Component_BP_C>();
	}
};
static_assert(alignof(UGrass2_Component_BP_C) == 0x000010, "Wrong alignment on UGrass2_Component_BP_C");
static_assert(sizeof(UGrass2_Component_BP_C) == 0x000800, "Wrong size on UGrass2_Component_BP_C");

}

