#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HE_LookAtLocationSeq

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK
{

// UserDefinedStruct HE_LookAtLocationSeq.HE_LookAtLocationSeq
// 0x0018 (0x0018 - 0x0000)
struct FHE_LookAtLocationSeq final
{
public:
	struct FVector                                LocationtoLook_15_08279B704682B57A7B58B18AAEEB7C94; // 0x0000(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Smooth_5_454C4AB74997F23D045944B6901E1DA9;         // 0x000C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         TurnSpeedSec_9_F1ED92664D8E504C55E2B299A1C16F4F;   // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         KeepLookingDurationSec_13_46B29F5047553D83F96803B9CEE30F22; // 0x0014(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(FHE_LookAtLocationSeq) == 0x000004, "Wrong alignment on FHE_LookAtLocationSeq");
static_assert(sizeof(FHE_LookAtLocationSeq) == 0x000018, "Wrong size on FHE_LookAtLocationSeq");
static_assert(offsetof(FHE_LookAtLocationSeq, LocationtoLook_15_08279B704682B57A7B58B18AAEEB7C94) == 0x000000, "Member 'FHE_LookAtLocationSeq::LocationtoLook_15_08279B704682B57A7B58B18AAEEB7C94' has a wrong offset!");
static_assert(offsetof(FHE_LookAtLocationSeq, Smooth_5_454C4AB74997F23D045944B6901E1DA9) == 0x00000C, "Member 'FHE_LookAtLocationSeq::Smooth_5_454C4AB74997F23D045944B6901E1DA9' has a wrong offset!");
static_assert(offsetof(FHE_LookAtLocationSeq, TurnSpeedSec_9_F1ED92664D8E504C55E2B299A1C16F4F) == 0x000010, "Member 'FHE_LookAtLocationSeq::TurnSpeedSec_9_F1ED92664D8E504C55E2B299A1C16F4F' has a wrong offset!");
static_assert(offsetof(FHE_LookAtLocationSeq, KeepLookingDurationSec_13_46B29F5047553D83F96803B9CEE30F22) == 0x000014, "Member 'FHE_LookAtLocationSeq::KeepLookingDurationSec_13_46B29F5047553D83F96803B9CEE30F22' has a wrong offset!");

}

