#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Lobby_Name_Box

#include "Basic.hpp"

#include "Lobby_Name_Box_classes.hpp"
#include "Lobby_Name_Box_parameters.hpp"


namespace SDK
{

// Function Lobby_Name_Box.Lobby_Name_Box_C.ExecuteUbergraph_Lobby_Name_Box
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULobby_Name_Box_C::ExecuteUbergraph_Lobby_Name_Box(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Lobby_Name_Box_C", "ExecuteUbergraph_Lobby_Name_Box");

	Params::Lobby_Name_Box_C_ExecuteUbergraph_Lobby_Name_Box Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Lobby_Name_Box.Lobby_Name_Box_C.BndEvt__Lobby_Name_Box_EditableTextBox_Name_K2Node_ComponentBoundEvent_0_OnEditableTextBoxChangedEvent__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// const class FText&                      Text                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void ULobby_Name_Box_C::BndEvt__Lobby_Name_Box_EditableTextBox_Name_K2Node_ComponentBoundEvent_0_OnEditableTextBoxChangedEvent__DelegateSignature(const class FText& Text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Lobby_Name_Box_C", "BndEvt__Lobby_Name_Box_EditableTextBox_Name_K2Node_ComponentBoundEvent_0_OnEditableTextBoxChangedEvent__DelegateSignature");

	Params::Lobby_Name_Box_C_BndEvt__Lobby_Name_Box_EditableTextBox_Name_K2Node_ComponentBoundEvent_0_OnEditableTextBoxChangedEvent__DelegateSignature Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Lobby_Name_Box.Lobby_Name_Box_C.CanClose
// (Public, BlueprintCallable, BlueprintEvent)

void ULobby_Name_Box_C::CanClose()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Lobby_Name_Box_C", "CanClose");

	UObject::ProcessEvent(Func, nullptr);
}

}

