#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayerEQSQuery

#include "Basic.hpp"

#include "AIModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PlayerEQSQuery.PlayerEQSQuery_C
// 0x0000 (0x0030 - 0x0030)
class PlayerEQSQuery::UPlayerEQSQuery_C final : public UEnvQueryContext_BlueprintBase
{
public:
	void ProvideActorsSet(class UObject* QuerierObject, class AActor* QuerierActor, TArray<class AActor*>* ResultingActorsSet) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BlueprintGeneratedClass PlayerEQSQuery.PlayerEQSQuery_C", true, "PlayerEQSQuery_C">();
	}
	static class PlayerEQSQuery::UPlayerEQSQuery_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<PlayerEQSQuery::UPlayerEQSQuery_C>();
	}
};
static_assert(alignof(PlayerEQSQuery::UPlayerEQSQuery_C) == 0x000008, "Wrong alignment on PlayerEQSQuery::UPlayerEQSQuery_C");
static_assert(sizeof(PlayerEQSQuery::UPlayerEQSQuery_C) == 0x000030, "Wrong size on PlayerEQSQuery::UPlayerEQSQuery_C");

}

