#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Calc

#include "Basic.hpp"

#include "UI_Calc_classes.hpp"
#include "UI_Calc_parameters.hpp"


namespace SDK
{

// Function UI_Calc.UI_Calc_C.ExecuteUbergraph_UI_Calc
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Calc_C::ExecuteUbergraph_UI_Calc(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Calc_C", "ExecuteUbergraph_UI_Calc");

	Params::UI_Calc_C_ExecuteUbergraph_UI_Calc Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Calc.UI_Calc_C.BndEvt__1_K2Node_ComponentBoundEvent_0_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Calc_C::BndEvt__1_K2Node_ComponentBoundEvent_0_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Calc_C", "BndEvt__1_K2Node_ComponentBoundEvent_0_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Calc.UI_Calc_C.BndEvt__equal_K2Node_ComponentBoundEvent_16_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Calc_C::BndEvt__equal_K2Node_ComponentBoundEvent_16_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Calc_C", "BndEvt__equal_K2Node_ComponentBoundEvent_16_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Calc.UI_Calc_C.Compute
// (BlueprintCallable, BlueprintEvent)

void UUI_Calc_C::Compute()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Calc_C", "Compute");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Calc.UI_Calc_C.BndEvt__dot_K2Node_ComponentBoundEvent_15_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Calc_C::BndEvt__dot_K2Node_ComponentBoundEvent_15_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Calc_C", "BndEvt__dot_K2Node_ComponentBoundEvent_15_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Calc.UI_Calc_C.BndEvt__Minus_K2Node_ComponentBoundEvent_14_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Calc_C::BndEvt__Minus_K2Node_ComponentBoundEvent_14_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Calc_C", "BndEvt__Minus_K2Node_ComponentBoundEvent_14_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Calc.UI_Calc_C.BndEvt__Multiply_K2Node_ComponentBoundEvent_13_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Calc_C::BndEvt__Multiply_K2Node_ComponentBoundEvent_13_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Calc_C", "BndEvt__Multiply_K2Node_ComponentBoundEvent_13_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Calc.UI_Calc_C.BndEvt__plus_K2Node_ComponentBoundEvent_12_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Calc_C::BndEvt__plus_K2Node_ComponentBoundEvent_12_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Calc_C", "BndEvt__plus_K2Node_ComponentBoundEvent_12_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Calc.UI_Calc_C.BndEvt__divide_K2Node_ComponentBoundEvent_11_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Calc_C::BndEvt__divide_K2Node_ComponentBoundEvent_11_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Calc_C", "BndEvt__divide_K2Node_ComponentBoundEvent_11_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Calc.UI_Calc_C.BndEvt__clear_K2Node_ComponentBoundEvent_10_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Calc_C::BndEvt__clear_K2Node_ComponentBoundEvent_10_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Calc_C", "BndEvt__clear_K2Node_ComponentBoundEvent_10_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Calc.UI_Calc_C.BndEvt__divide_K2Node_ComponentBoundEvent_9_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Calc_C::BndEvt__divide_K2Node_ComponentBoundEvent_9_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Calc_C", "BndEvt__divide_K2Node_ComponentBoundEvent_9_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Calc.UI_Calc_C.BndEvt__9_K2Node_ComponentBoundEvent_8_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Calc_C::BndEvt__9_K2Node_ComponentBoundEvent_8_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Calc_C", "BndEvt__9_K2Node_ComponentBoundEvent_8_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Calc.UI_Calc_C.BndEvt__8_K2Node_ComponentBoundEvent_7_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Calc_C::BndEvt__8_K2Node_ComponentBoundEvent_7_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Calc_C", "BndEvt__8_K2Node_ComponentBoundEvent_7_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Calc.UI_Calc_C.BndEvt__7_K2Node_ComponentBoundEvent_6_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Calc_C::BndEvt__7_K2Node_ComponentBoundEvent_6_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Calc_C", "BndEvt__7_K2Node_ComponentBoundEvent_6_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Calc.UI_Calc_C.BndEvt__6_K2Node_ComponentBoundEvent_5_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Calc_C::BndEvt__6_K2Node_ComponentBoundEvent_5_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Calc_C", "BndEvt__6_K2Node_ComponentBoundEvent_5_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Calc.UI_Calc_C.BndEvt__5_K2Node_ComponentBoundEvent_4_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Calc_C::BndEvt__5_K2Node_ComponentBoundEvent_4_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Calc_C", "BndEvt__5_K2Node_ComponentBoundEvent_4_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Calc.UI_Calc_C.BndEvt__4_K2Node_ComponentBoundEvent_3_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Calc_C::BndEvt__4_K2Node_ComponentBoundEvent_3_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Calc_C", "BndEvt__4_K2Node_ComponentBoundEvent_3_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Calc.UI_Calc_C.BndEvt__3_K2Node_ComponentBoundEvent_2_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Calc_C::BndEvt__3_K2Node_ComponentBoundEvent_2_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Calc_C", "BndEvt__3_K2Node_ComponentBoundEvent_2_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Calc.UI_Calc_C.BndEvt__2_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Calc_C::BndEvt__2_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Calc_C", "BndEvt__2_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}

}

