#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Drag

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Drag.UI_Drag_C
// 0x0088 (0x02E8 - 0x0260)
class UUI_Drag_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBorder*                                Body;                                              // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                CloseBTN;                                          // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                Header;                                            // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         HorizontalBox_main;                                // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               MainBox;                                           // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             ProgName;                                          // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                SetAsBackground;                                   // 0x0298(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FVector2D                              GrabOffset;                                        // 0x02A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUI_Drag_C*                             Draggetwidget;                                     // 0x02A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Width_O;                                           // 0x02B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Height_O;                                          // 0x02B4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_Init_C*                             ParentActor;                                       // 0x02B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UTexture2D*                             Image;                                             // 0x02C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUI_Desktop_C*                          Desktop;                                           // 0x02C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(bool IsGrabbed, class UUI_Drag_C* Window)> DragWindow;             // 0x02D0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          IsWindowGrabbed;                                   // 0x02E0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_UI_Drag(int32 EntryPoint);
	void PlayClick();
	void BndEvt__UI_Drag_CloseBTN_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature();
	void CloseProgram(bool RestoreFocus);
	void BndEvt__Button_64_K2Node_ComponentBoundEvent_0_OnButtonPressedEvent__DelegateSignature();
	void SetProgram(class UWidget* Widget, float Width_O_0, float Height_O_0);
	void ForceDeleteBack();
	void BndEvt__SetAsBackground_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature();
	struct FEventReply On_Header_MouseButtonDown_0(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent);
	struct FEventReply OnMouseButtonUp(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent);
	struct FEventReply OnKeyDown(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Drag_C">();
	}
	static class UUI_Drag_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Drag_C>();
	}
};
static_assert(alignof(UUI_Drag_C) == 0x000008, "Wrong alignment on UUI_Drag_C");
static_assert(sizeof(UUI_Drag_C) == 0x0002E8, "Wrong size on UUI_Drag_C");
static_assert(offsetof(UUI_Drag_C, UberGraphFrame) == 0x000260, "Member 'UUI_Drag_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUI_Drag_C, Body) == 0x000268, "Member 'UUI_Drag_C::Body' has a wrong offset!");
static_assert(offsetof(UUI_Drag_C, CloseBTN) == 0x000270, "Member 'UUI_Drag_C::CloseBTN' has a wrong offset!");
static_assert(offsetof(UUI_Drag_C, Header) == 0x000278, "Member 'UUI_Drag_C::Header' has a wrong offset!");
static_assert(offsetof(UUI_Drag_C, HorizontalBox_main) == 0x000280, "Member 'UUI_Drag_C::HorizontalBox_main' has a wrong offset!");
static_assert(offsetof(UUI_Drag_C, MainBox) == 0x000288, "Member 'UUI_Drag_C::MainBox' has a wrong offset!");
static_assert(offsetof(UUI_Drag_C, ProgName) == 0x000290, "Member 'UUI_Drag_C::ProgName' has a wrong offset!");
static_assert(offsetof(UUI_Drag_C, SetAsBackground) == 0x000298, "Member 'UUI_Drag_C::SetAsBackground' has a wrong offset!");
static_assert(offsetof(UUI_Drag_C, GrabOffset) == 0x0002A0, "Member 'UUI_Drag_C::GrabOffset' has a wrong offset!");
static_assert(offsetof(UUI_Drag_C, Draggetwidget) == 0x0002A8, "Member 'UUI_Drag_C::Draggetwidget' has a wrong offset!");
static_assert(offsetof(UUI_Drag_C, Width_O) == 0x0002B0, "Member 'UUI_Drag_C::Width_O' has a wrong offset!");
static_assert(offsetof(UUI_Drag_C, Height_O) == 0x0002B4, "Member 'UUI_Drag_C::Height_O' has a wrong offset!");
static_assert(offsetof(UUI_Drag_C, ParentActor) == 0x0002B8, "Member 'UUI_Drag_C::ParentActor' has a wrong offset!");
static_assert(offsetof(UUI_Drag_C, Image) == 0x0002C0, "Member 'UUI_Drag_C::Image' has a wrong offset!");
static_assert(offsetof(UUI_Drag_C, Desktop) == 0x0002C8, "Member 'UUI_Drag_C::Desktop' has a wrong offset!");
static_assert(offsetof(UUI_Drag_C, DragWindow) == 0x0002D0, "Member 'UUI_Drag_C::DragWindow' has a wrong offset!");
static_assert(offsetof(UUI_Drag_C, IsWindowGrabbed) == 0x0002E0, "Member 'UUI_Drag_C::IsWindowGrabbed' has a wrong offset!");

}

