#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Menu_Lobby_Switcher

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "UMG_structs.hpp"
#include "InputCore_structs.hpp"


namespace SDK::Params
{

// Function UI_Menu_Lobby_Switcher.UI_Menu_Lobby_Switcher_C.ExecuteUbergraph_UI_Menu_Lobby_Switcher
// 0x01C0 (0x01C0 - 0x0000)
struct UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_2;                              // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Temp_float_Variable;                               // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_1;                             // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_LastIndex_ReturnValue;              // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_1;             // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_25[0x3];                                       // 0x0025(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x002C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2D[0x3];                                       // 0x002D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable;                                 // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_3;                              // 0x0034(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x0035(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_36[0x2];                                       // 0x0036(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_Select_Default;                             // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_1;            // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue_1;          // 0x0044(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_45[0x3];                                       // 0x0045(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x004C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_2;             // 0x004D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_4;                              // 0x004E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default_1;                           // 0x004F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Select_Default_2;                           // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsHovered;                            // 0x0054(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_55[0x3];                                       // 0x0055(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0058(0x0028)()
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_1;                    // 0x0080(0x0028)()
	bool                                          K2Node_Event_IsFocused;                            // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A9[0x7];                                       // 0x00A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateColor                            K2Node_Select_Default_3;                           // 0x00B0(0x0028)()
	bool                                          CallFunc_IsVisible_ReturnValue;                    // 0x00D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsVisible_ReturnValue_1;                  // 0x00D9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_DA[0x6];                                       // 0x00DA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateFontInfo                         CallFunc_Get_Font_Culture_Checked_OutFont;         // 0x00E0(0x0058)(HasGetValueTypeHash)
	class FText                                   CallFunc_GetText_ReturnValue;                      // 0x0138(0x0018)()
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x0150(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsEnabled;                            // 0x0160(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_161[0x7];                                      // 0x0161(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Split_LeftS;                              // 0x0168(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Split_RightS;                             // 0x0178(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_Split_ReturnValue;                        // 0x0188(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_189[0x7];                                      // 0x0189(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0190(0x0018)()
	float                                         K2Node_Select_Default_4;                           // 0x01A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1AC[0x4];                                      // 0x01AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBPI_UserInterface_C>  CallFunc_ToggleEnabled_self_CastInput;             // 0x01B0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher) == 0x000008, "Wrong alignment on UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher");
static_assert(sizeof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher) == 0x0001C0, "Wrong size on UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, EntryPoint) == 0x000000, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::EntryPoint' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, Temp_bool_Variable) == 0x000004, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, Temp_byte_Variable) == 0x000005, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, Temp_byte_Variable_1) == 0x000006, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, Temp_bool_Variable_1) == 0x000007, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, Temp_bool_Variable_2) == 0x000008, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::Temp_bool_Variable_2' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, Temp_float_Variable) == 0x00000C, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::Temp_float_Variable' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, Temp_float_Variable_1) == 0x000010, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::Temp_float_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, CallFunc_Array_Length_ReturnValue) == 0x000014, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, CallFunc_Greater_IntInt_ReturnValue) == 0x000018, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, CallFunc_Array_LastIndex_ReturnValue) == 0x00001C, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::CallFunc_Array_LastIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, CallFunc_Add_IntInt_ReturnValue) == 0x000020, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, CallFunc_Greater_IntInt_ReturnValue_1) == 0x000024, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::CallFunc_Greater_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, CallFunc_Subtract_IntInt_ReturnValue) == 0x000028, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, CallFunc_Less_IntInt_ReturnValue) == 0x00002C, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, Temp_int_Variable) == 0x000030, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, Temp_bool_Variable_3) == 0x000034, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::Temp_bool_Variable_3' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x000035, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, K2Node_Select_Default) == 0x000038, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, CallFunc_Array_Length_ReturnValue_1) == 0x00003C, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, CallFunc_Subtract_IntInt_ReturnValue_1) == 0x000040, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::CallFunc_Subtract_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, CallFunc_EqualEqual_IntInt_ReturnValue_1) == 0x000044, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::CallFunc_EqualEqual_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, CallFunc_Array_Length_ReturnValue_2) == 0x000048, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::CallFunc_Array_Length_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, K2Node_Event_IsDesignTime) == 0x00004C, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, CallFunc_Greater_IntInt_ReturnValue_2) == 0x00004D, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::CallFunc_Greater_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, Temp_bool_Variable_4) == 0x00004E, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::Temp_bool_Variable_4' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, K2Node_Select_Default_1) == 0x00004F, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, K2Node_Select_Default_2) == 0x000050, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::K2Node_Select_Default_2' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, K2Node_Event_IsHovered) == 0x000054, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::K2Node_Event_IsHovered' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, K2Node_MakeStruct_SlateColor) == 0x000058, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::K2Node_MakeStruct_SlateColor' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, K2Node_MakeStruct_SlateColor_1) == 0x000080, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::K2Node_MakeStruct_SlateColor_1' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, K2Node_Event_IsFocused) == 0x0000A8, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::K2Node_Event_IsFocused' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, K2Node_Select_Default_3) == 0x0000B0, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::K2Node_Select_Default_3' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, CallFunc_IsVisible_ReturnValue) == 0x0000D8, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::CallFunc_IsVisible_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, CallFunc_IsVisible_ReturnValue_1) == 0x0000D9, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::CallFunc_IsVisible_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, CallFunc_Get_Font_Culture_Checked_OutFont) == 0x0000E0, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::CallFunc_Get_Font_Culture_Checked_OutFont' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, CallFunc_GetText_ReturnValue) == 0x000138, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::CallFunc_GetText_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, CallFunc_Conv_TextToString_ReturnValue) == 0x000150, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::CallFunc_Conv_TextToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, K2Node_Event_IsEnabled) == 0x000160, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::K2Node_Event_IsEnabled' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, CallFunc_Split_LeftS) == 0x000168, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::CallFunc_Split_LeftS' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, CallFunc_Split_RightS) == 0x000178, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::CallFunc_Split_RightS' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, CallFunc_Split_ReturnValue) == 0x000188, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::CallFunc_Split_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, CallFunc_Conv_StringToText_ReturnValue) == 0x000190, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, K2Node_Select_Default_4) == 0x0001A8, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::K2Node_Select_Default_4' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher, CallFunc_ToggleEnabled_self_CastInput) == 0x0001B0, "Member 'UI_Menu_Lobby_Switcher_C_ExecuteUbergraph_UI_Menu_Lobby_Switcher::CallFunc_ToggleEnabled_self_CastInput' has a wrong offset!");

// Function UI_Menu_Lobby_Switcher.UI_Menu_Lobby_Switcher_C.ToggleEnabled
// 0x0001 (0x0001 - 0x0000)
struct UI_Menu_Lobby_Switcher_C_ToggleEnabled final
{
public:
	bool                                          IsEnabled;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_Menu_Lobby_Switcher_C_ToggleEnabled) == 0x000001, "Wrong alignment on UI_Menu_Lobby_Switcher_C_ToggleEnabled");
static_assert(sizeof(UI_Menu_Lobby_Switcher_C_ToggleEnabled) == 0x000001, "Wrong size on UI_Menu_Lobby_Switcher_C_ToggleEnabled");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ToggleEnabled, IsEnabled) == 0x000000, "Member 'UI_Menu_Lobby_Switcher_C_ToggleEnabled::IsEnabled' has a wrong offset!");

// Function UI_Menu_Lobby_Switcher.UI_Menu_Lobby_Switcher_C.ToggleFocus
// 0x0001 (0x0001 - 0x0000)
struct UI_Menu_Lobby_Switcher_C_ToggleFocus final
{
public:
	bool                                          IsFocused;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_Menu_Lobby_Switcher_C_ToggleFocus) == 0x000001, "Wrong alignment on UI_Menu_Lobby_Switcher_C_ToggleFocus");
static_assert(sizeof(UI_Menu_Lobby_Switcher_C_ToggleFocus) == 0x000001, "Wrong size on UI_Menu_Lobby_Switcher_C_ToggleFocus");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ToggleFocus, IsFocused) == 0x000000, "Member 'UI_Menu_Lobby_Switcher_C_ToggleFocus::IsFocused' has a wrong offset!");

// Function UI_Menu_Lobby_Switcher.UI_Menu_Lobby_Switcher_C.ToggleHover
// 0x0001 (0x0001 - 0x0000)
struct UI_Menu_Lobby_Switcher_C_ToggleHover final
{
public:
	bool                                          IsHovered_0;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_Menu_Lobby_Switcher_C_ToggleHover) == 0x000001, "Wrong alignment on UI_Menu_Lobby_Switcher_C_ToggleHover");
static_assert(sizeof(UI_Menu_Lobby_Switcher_C_ToggleHover) == 0x000001, "Wrong size on UI_Menu_Lobby_Switcher_C_ToggleHover");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_ToggleHover, IsHovered_0) == 0x000000, "Member 'UI_Menu_Lobby_Switcher_C_ToggleHover::IsHovered_0' has a wrong offset!");

// Function UI_Menu_Lobby_Switcher.UI_Menu_Lobby_Switcher_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct UI_Menu_Lobby_Switcher_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_Menu_Lobby_Switcher_C_PreConstruct) == 0x000001, "Wrong alignment on UI_Menu_Lobby_Switcher_C_PreConstruct");
static_assert(sizeof(UI_Menu_Lobby_Switcher_C_PreConstruct) == 0x000001, "Wrong size on UI_Menu_Lobby_Switcher_C_PreConstruct");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'UI_Menu_Lobby_Switcher_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function UI_Menu_Lobby_Switcher.UI_Menu_Lobby_Switcher_C.GetCurrentMode
// 0x0030 (0x0030 - 0x0000)
struct UI_Menu_Lobby_Switcher_C_GetCurrentMode final
{
public:
	class FText                                   ModeName;                                          // 0x0000(0x0018)(Parm, OutParm)
	class FText                                   CallFunc_Array_Get_Item;                           // 0x0018(0x0018)()
};
static_assert(alignof(UI_Menu_Lobby_Switcher_C_GetCurrentMode) == 0x000008, "Wrong alignment on UI_Menu_Lobby_Switcher_C_GetCurrentMode");
static_assert(sizeof(UI_Menu_Lobby_Switcher_C_GetCurrentMode) == 0x000030, "Wrong size on UI_Menu_Lobby_Switcher_C_GetCurrentMode");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_GetCurrentMode, ModeName) == 0x000000, "Member 'UI_Menu_Lobby_Switcher_C_GetCurrentMode::ModeName' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_GetCurrentMode, CallFunc_Array_Get_Item) == 0x000018, "Member 'UI_Menu_Lobby_Switcher_C_GetCurrentMode::CallFunc_Array_Get_Item' has a wrong offset!");

// Function UI_Menu_Lobby_Switcher.UI_Menu_Lobby_Switcher_C.OnPreviewKeyDown
// 0x02B8 (0x02B8 - 0x0000)
struct UI_Menu_Lobby_Switcher_C_OnPreviewKeyDown final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	struct FKeyEvent                              InKeyEvent;                                        // 0x0038(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm)
	struct FEventReply                            ReturnValue;                                       // 0x0070(0x00B8)(Parm, OutParm, ReturnParm)
	struct FKey                                   CallFunc_GetKey_ReturnValue;                       // 0x0128(0x0018)(HasGetValueTypeHash)
	struct FEventReply                            CallFunc_Handled_ReturnValue;                      // 0x0140(0x00B8)()
	bool                                          CallFunc_EqualEqual_KeyKey_ReturnValue;            // 0x01F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_KeyKey_ReturnValue_1;          // 0x01F9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1FA[0x6];                                      // 0x01FA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FEventReply                            CallFunc_Handled_ReturnValue_1;                    // 0x0200(0x00B8)()
};
static_assert(alignof(UI_Menu_Lobby_Switcher_C_OnPreviewKeyDown) == 0x000008, "Wrong alignment on UI_Menu_Lobby_Switcher_C_OnPreviewKeyDown");
static_assert(sizeof(UI_Menu_Lobby_Switcher_C_OnPreviewKeyDown) == 0x0002B8, "Wrong size on UI_Menu_Lobby_Switcher_C_OnPreviewKeyDown");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_OnPreviewKeyDown, MyGeometry) == 0x000000, "Member 'UI_Menu_Lobby_Switcher_C_OnPreviewKeyDown::MyGeometry' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_OnPreviewKeyDown, InKeyEvent) == 0x000038, "Member 'UI_Menu_Lobby_Switcher_C_OnPreviewKeyDown::InKeyEvent' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_OnPreviewKeyDown, ReturnValue) == 0x000070, "Member 'UI_Menu_Lobby_Switcher_C_OnPreviewKeyDown::ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_OnPreviewKeyDown, CallFunc_GetKey_ReturnValue) == 0x000128, "Member 'UI_Menu_Lobby_Switcher_C_OnPreviewKeyDown::CallFunc_GetKey_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_OnPreviewKeyDown, CallFunc_Handled_ReturnValue) == 0x000140, "Member 'UI_Menu_Lobby_Switcher_C_OnPreviewKeyDown::CallFunc_Handled_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_OnPreviewKeyDown, CallFunc_EqualEqual_KeyKey_ReturnValue) == 0x0001F8, "Member 'UI_Menu_Lobby_Switcher_C_OnPreviewKeyDown::CallFunc_EqualEqual_KeyKey_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_OnPreviewKeyDown, CallFunc_EqualEqual_KeyKey_ReturnValue_1) == 0x0001F9, "Member 'UI_Menu_Lobby_Switcher_C_OnPreviewKeyDown::CallFunc_EqualEqual_KeyKey_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Menu_Lobby_Switcher_C_OnPreviewKeyDown, CallFunc_Handled_ReturnValue_1) == 0x000200, "Member 'UI_Menu_Lobby_Switcher_C_OnPreviewKeyDown::CallFunc_Handled_ReturnValue_1' has a wrong offset!");

}

