#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Menu_Programm

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ST_UI_Mission_structs.hpp"
#include "UMG_classes.hpp"
#include "SlateCore_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Menu_Programm.UI_Menu_Programm_C
// 0x00C8 (0x0328 - 0x0260)
class UUI_Menu_Programm_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       FadeIn;                                            // 0x0268(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UUI_Menu_Button_C*                      BackButton;                                        // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           CP_Variators;                                      // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_1;                                           // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_2;                                           // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_24;                                          // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Img_Display_Icon;                                  // 0x0298(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Img_VariatorsBG01;                                 // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScrollBox*                             SC_MissionList;                                    // 0x02A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Menu_Button_C*                      SelectButton;                                      // 0x02B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Txt_Description;                                   // 0x02B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Txt_Variators;                                     // 0x02C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Txt_WindowName;                                    // 0x02C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Menu_Programm_Mission_C*            UI_Menu_Programm_Mission;                          // 0x02D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Menu_Programm_Mission_C*            UI_Menu_Programm_Mission_1;                        // 0x02D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Menu_Programm_Mission_C*            UI_Menu_Programm_Mission_2;                        // 0x02E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Menu_Programm_Mission_C*            UI_Menu_Programm_Mission_3;                        // 0x02E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Menu_Programm_Mission_C*            UI_Menu_Programm_Mission_4;                        // 0x02F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VB_MissionList;                                    // 0x02F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TArray<class UUI_Menu_Programm_Mission_C*>    UI_Missions;                                       // 0x0300(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	TArray<struct FST_UI_Mission>                 Missions;                                          // 0x0310(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	int32                                         CurrentMissionIndex;                               // 0x0320(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_UI_Menu_Programm(int32 EntryPoint);
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void ToggleFocus(bool IsFocused);
	void SelectMission();
	void CloseMenu();
	void BndEvt__UI_Menu_Programm_UI_Menu_Button_1_K2Node_ComponentBoundEvent_1_OnClick__DelegateSignature();
	void Init(const class FText& Assignment);
	void PreConstruct(bool IsDesignTime);
	void BndEvt__UI_Menu_Programm_UI_Menu_Button_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature();
	void UpdateMissionList();
	void UpdateDescription(const struct FST_UI_Mission& Mission);
	void Select(const int32 Index_0, const struct FST_UI_Mission& Mission);
	void Construct();
	void ToggleEnabled(bool IsEnabled);
	void ToggleHover(bool IsHovered_0);
	struct FEventReply OnKeyDown(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent);
	class UWidget* CustomNavigation(EUINavigation Navigation_0);
	struct FEventReply OnPreviewKeyDown(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent);
	class FText Get_Txt_Description_Text_0();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Menu_Programm_C">();
	}
	static class UUI_Menu_Programm_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Menu_Programm_C>();
	}
};
static_assert(alignof(UUI_Menu_Programm_C) == 0x000008, "Wrong alignment on UUI_Menu_Programm_C");
static_assert(sizeof(UUI_Menu_Programm_C) == 0x000328, "Wrong size on UUI_Menu_Programm_C");
static_assert(offsetof(UUI_Menu_Programm_C, UberGraphFrame) == 0x000260, "Member 'UUI_Menu_Programm_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUI_Menu_Programm_C, FadeIn) == 0x000268, "Member 'UUI_Menu_Programm_C::FadeIn' has a wrong offset!");
static_assert(offsetof(UUI_Menu_Programm_C, BackButton) == 0x000270, "Member 'UUI_Menu_Programm_C::BackButton' has a wrong offset!");
static_assert(offsetof(UUI_Menu_Programm_C, CP_Variators) == 0x000278, "Member 'UUI_Menu_Programm_C::CP_Variators' has a wrong offset!");
static_assert(offsetof(UUI_Menu_Programm_C, Image_1) == 0x000280, "Member 'UUI_Menu_Programm_C::Image_1' has a wrong offset!");
static_assert(offsetof(UUI_Menu_Programm_C, Image_2) == 0x000288, "Member 'UUI_Menu_Programm_C::Image_2' has a wrong offset!");
static_assert(offsetof(UUI_Menu_Programm_C, Image_24) == 0x000290, "Member 'UUI_Menu_Programm_C::Image_24' has a wrong offset!");
static_assert(offsetof(UUI_Menu_Programm_C, Img_Display_Icon) == 0x000298, "Member 'UUI_Menu_Programm_C::Img_Display_Icon' has a wrong offset!");
static_assert(offsetof(UUI_Menu_Programm_C, Img_VariatorsBG01) == 0x0002A0, "Member 'UUI_Menu_Programm_C::Img_VariatorsBG01' has a wrong offset!");
static_assert(offsetof(UUI_Menu_Programm_C, SC_MissionList) == 0x0002A8, "Member 'UUI_Menu_Programm_C::SC_MissionList' has a wrong offset!");
static_assert(offsetof(UUI_Menu_Programm_C, SelectButton) == 0x0002B0, "Member 'UUI_Menu_Programm_C::SelectButton' has a wrong offset!");
static_assert(offsetof(UUI_Menu_Programm_C, Txt_Description) == 0x0002B8, "Member 'UUI_Menu_Programm_C::Txt_Description' has a wrong offset!");
static_assert(offsetof(UUI_Menu_Programm_C, Txt_Variators) == 0x0002C0, "Member 'UUI_Menu_Programm_C::Txt_Variators' has a wrong offset!");
static_assert(offsetof(UUI_Menu_Programm_C, Txt_WindowName) == 0x0002C8, "Member 'UUI_Menu_Programm_C::Txt_WindowName' has a wrong offset!");
static_assert(offsetof(UUI_Menu_Programm_C, UI_Menu_Programm_Mission) == 0x0002D0, "Member 'UUI_Menu_Programm_C::UI_Menu_Programm_Mission' has a wrong offset!");
static_assert(offsetof(UUI_Menu_Programm_C, UI_Menu_Programm_Mission_1) == 0x0002D8, "Member 'UUI_Menu_Programm_C::UI_Menu_Programm_Mission_1' has a wrong offset!");
static_assert(offsetof(UUI_Menu_Programm_C, UI_Menu_Programm_Mission_2) == 0x0002E0, "Member 'UUI_Menu_Programm_C::UI_Menu_Programm_Mission_2' has a wrong offset!");
static_assert(offsetof(UUI_Menu_Programm_C, UI_Menu_Programm_Mission_3) == 0x0002E8, "Member 'UUI_Menu_Programm_C::UI_Menu_Programm_Mission_3' has a wrong offset!");
static_assert(offsetof(UUI_Menu_Programm_C, UI_Menu_Programm_Mission_4) == 0x0002F0, "Member 'UUI_Menu_Programm_C::UI_Menu_Programm_Mission_4' has a wrong offset!");
static_assert(offsetof(UUI_Menu_Programm_C, VB_MissionList) == 0x0002F8, "Member 'UUI_Menu_Programm_C::VB_MissionList' has a wrong offset!");
static_assert(offsetof(UUI_Menu_Programm_C, UI_Missions) == 0x000300, "Member 'UUI_Menu_Programm_C::UI_Missions' has a wrong offset!");
static_assert(offsetof(UUI_Menu_Programm_C, Missions) == 0x000310, "Member 'UUI_Menu_Programm_C::Missions' has a wrong offset!");
static_assert(offsetof(UUI_Menu_Programm_C, CurrentMissionIndex) == 0x000320, "Member 'UUI_Menu_Programm_C::CurrentMissionIndex' has a wrong offset!");

}

