#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Menu_Programm_Mission

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ST_UI_Mission_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Menu_Programm_Mission.UI_Menu_Programm_Mission_C
// 0x00F0 (0x0350 - 0x0260)
class UUI_Menu_Programm_Mission_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Img_BG;                                            // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Img_State;                                         // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Img_TrialLevel;                                    // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Txt_Index;                                         // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Txt_Name;                                          // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Txt_Trial;                                         // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               M_TrialLevel;                                      // 0x0298(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FST_UI_Mission                         Mission;                                           // 0x02A0(0x0098)(Edit, BlueprintVisible, ExposeOnSpawn, HasGetValueTypeHash)
	int32                                         Index_0;                                           // 0x0338(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_33C[0x4];                                      // 0x033C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_Menu_Programm_C*                    UI_Menu_Programm;                                  // 0x0340(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          bSelected;                                         // 0x0348(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_UI_Menu_Programm_Mission(int32 EntryPoint);
	void ToggleFocus(bool IsFocused);
	void Select();
	void OnMouseLeave(const struct FPointerEvent& MouseEvent);
	void OnMouseEnter(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent);
	void UpdateSelect(bool bSelected_0);
	void Construct();
	void ToggleEnabled(bool IsEnabled);
	void ToggleHover(bool IsHovered_0);
	struct FEventReply OnMouseButtonDown(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent);
	void Get_Text_Color(struct FSlateColor* SlateColor);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Menu_Programm_Mission_C">();
	}
	static class UUI_Menu_Programm_Mission_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Menu_Programm_Mission_C>();
	}
};
static_assert(alignof(UUI_Menu_Programm_Mission_C) == 0x000008, "Wrong alignment on UUI_Menu_Programm_Mission_C");
static_assert(sizeof(UUI_Menu_Programm_Mission_C) == 0x000350, "Wrong size on UUI_Menu_Programm_Mission_C");
static_assert(offsetof(UUI_Menu_Programm_Mission_C, UberGraphFrame) == 0x000260, "Member 'UUI_Menu_Programm_Mission_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUI_Menu_Programm_Mission_C, Img_BG) == 0x000268, "Member 'UUI_Menu_Programm_Mission_C::Img_BG' has a wrong offset!");
static_assert(offsetof(UUI_Menu_Programm_Mission_C, Img_State) == 0x000270, "Member 'UUI_Menu_Programm_Mission_C::Img_State' has a wrong offset!");
static_assert(offsetof(UUI_Menu_Programm_Mission_C, Img_TrialLevel) == 0x000278, "Member 'UUI_Menu_Programm_Mission_C::Img_TrialLevel' has a wrong offset!");
static_assert(offsetof(UUI_Menu_Programm_Mission_C, Txt_Index) == 0x000280, "Member 'UUI_Menu_Programm_Mission_C::Txt_Index' has a wrong offset!");
static_assert(offsetof(UUI_Menu_Programm_Mission_C, Txt_Name) == 0x000288, "Member 'UUI_Menu_Programm_Mission_C::Txt_Name' has a wrong offset!");
static_assert(offsetof(UUI_Menu_Programm_Mission_C, Txt_Trial) == 0x000290, "Member 'UUI_Menu_Programm_Mission_C::Txt_Trial' has a wrong offset!");
static_assert(offsetof(UUI_Menu_Programm_Mission_C, M_TrialLevel) == 0x000298, "Member 'UUI_Menu_Programm_Mission_C::M_TrialLevel' has a wrong offset!");
static_assert(offsetof(UUI_Menu_Programm_Mission_C, Mission) == 0x0002A0, "Member 'UUI_Menu_Programm_Mission_C::Mission' has a wrong offset!");
static_assert(offsetof(UUI_Menu_Programm_Mission_C, Index_0) == 0x000338, "Member 'UUI_Menu_Programm_Mission_C::Index_0' has a wrong offset!");
static_assert(offsetof(UUI_Menu_Programm_Mission_C, UI_Menu_Programm) == 0x000340, "Member 'UUI_Menu_Programm_Mission_C::UI_Menu_Programm' has a wrong offset!");
static_assert(offsetof(UUI_Menu_Programm_Mission_C, bSelected) == 0x000348, "Member 'UUI_Menu_Programm_Mission_C::bSelected' has a wrong offset!");

}

