#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Confirmation

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "UMG_structs.hpp"
#include "E_Comfirmation_structs.hpp"
#include "InputCore_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function W_Confirmation.W_Confirmation_C.ExecuteUbergraph_W_Confirmation
// 0x0170 (0x0170 - 0x0000)
struct W_Confirmation_C_ExecuteUbergraph_W_Confirmation final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0008(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0018(0x0010)(ZeroConstructor, NoDestructor)
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue;            // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue;          // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_FloatToText_ReturnValue;             // 0x0038(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0050(0x0040)(HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue;           // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_91[0x7];                                       // 0x0091(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0098(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x00A8(0x0018)()
	class FText                                   K2Node_Event_Title;                                // 0x00C0(0x0018)()
	class FText                                   K2Node_Event_Message;                              // 0x00D8(0x0018)()
	E_Comfirmation                                K2Node_Event_ConfirmationFor;                      // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x00F1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_SwitchEnum_CmpSuccess_1;                    // 0x00F2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x00F3(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x00F4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_F5[0x3];                                       // 0x00F5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue_1;            // 0x0100(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue_2;            // 0x0108(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue_3;            // 0x0110(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue_4;            // 0x0118(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBPI_UserInterface_C>  K2Node_DynamicCast_AsBPI_User_Interface;           // 0x0120(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0130(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_131[0x7];                                      // 0x0131(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue_5;            // 0x0138(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UDestroySessionCallbackProxy*           CallFunc_DestroySession_ReturnValue;               // 0x0140(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue_6;            // 0x0148(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x0150(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_151[0x7];                                      // 0x0151(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBPI_UserInterface_C>  K2Node_DynamicCast_AsBPI_User_Interface_1;         // 0x0158(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0168(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation) == 0x000008, "Wrong alignment on W_Confirmation_C_ExecuteUbergraph_W_Confirmation");
static_assert(sizeof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation) == 0x000170, "Wrong size on W_Confirmation_C_ExecuteUbergraph_W_Confirmation");
static_assert(offsetof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation, EntryPoint) == 0x000000, "Member 'W_Confirmation_C_ExecuteUbergraph_W_Confirmation::EntryPoint' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation, CallFunc_IsValid_ReturnValue) == 0x000004, "Member 'W_Confirmation_C_ExecuteUbergraph_W_Confirmation::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation, K2Node_CreateDelegate_OutputDelegate) == 0x000008, "Member 'W_Confirmation_C_ExecuteUbergraph_W_Confirmation::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation, K2Node_CreateDelegate_OutputDelegate_1) == 0x000018, "Member 'W_Confirmation_C_ExecuteUbergraph_W_Confirmation::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation, CallFunc_Add_FloatFloat_ReturnValue) == 0x000028, "Member 'W_Confirmation_C_ExecuteUbergraph_W_Confirmation::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation, CallFunc_Divide_FloatFloat_ReturnValue) == 0x00002C, "Member 'W_Confirmation_C_ExecuteUbergraph_W_Confirmation::CallFunc_Divide_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation, CallFunc_Subtract_FloatFloat_ReturnValue) == 0x000030, "Member 'W_Confirmation_C_ExecuteUbergraph_W_Confirmation::CallFunc_Subtract_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation, CallFunc_Conv_FloatToText_ReturnValue) == 0x000038, "Member 'W_Confirmation_C_ExecuteUbergraph_W_Confirmation::CallFunc_Conv_FloatToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation, K2Node_MakeStruct_FormatArgumentData) == 0x000050, "Member 'W_Confirmation_C_ExecuteUbergraph_W_Confirmation::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation, CallFunc_Greater_FloatFloat_ReturnValue) == 0x000090, "Member 'W_Confirmation_C_ExecuteUbergraph_W_Confirmation::CallFunc_Greater_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation, K2Node_MakeArray_Array) == 0x000098, "Member 'W_Confirmation_C_ExecuteUbergraph_W_Confirmation::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation, CallFunc_Format_ReturnValue) == 0x0000A8, "Member 'W_Confirmation_C_ExecuteUbergraph_W_Confirmation::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation, K2Node_Event_Title) == 0x0000C0, "Member 'W_Confirmation_C_ExecuteUbergraph_W_Confirmation::K2Node_Event_Title' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation, K2Node_Event_Message) == 0x0000D8, "Member 'W_Confirmation_C_ExecuteUbergraph_W_Confirmation::K2Node_Event_Message' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation, K2Node_Event_ConfirmationFor) == 0x0000F0, "Member 'W_Confirmation_C_ExecuteUbergraph_W_Confirmation::K2Node_Event_ConfirmationFor' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation, K2Node_SwitchEnum_CmpSuccess) == 0x0000F1, "Member 'W_Confirmation_C_ExecuteUbergraph_W_Confirmation::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation, K2Node_SwitchEnum_CmpSuccess_1) == 0x0000F2, "Member 'W_Confirmation_C_ExecuteUbergraph_W_Confirmation::K2Node_SwitchEnum_CmpSuccess_1' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation, CallFunc_IsValid_ReturnValue_1) == 0x0000F3, "Member 'W_Confirmation_C_ExecuteUbergraph_W_Confirmation::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation, CallFunc_IsValid_ReturnValue_2) == 0x0000F4, "Member 'W_Confirmation_C_ExecuteUbergraph_W_Confirmation::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation, CallFunc_GetOwningPlayer_ReturnValue) == 0x0000F8, "Member 'W_Confirmation_C_ExecuteUbergraph_W_Confirmation::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation, CallFunc_GetOwningPlayer_ReturnValue_1) == 0x000100, "Member 'W_Confirmation_C_ExecuteUbergraph_W_Confirmation::CallFunc_GetOwningPlayer_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation, CallFunc_GetOwningPlayer_ReturnValue_2) == 0x000108, "Member 'W_Confirmation_C_ExecuteUbergraph_W_Confirmation::CallFunc_GetOwningPlayer_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation, CallFunc_GetOwningPlayer_ReturnValue_3) == 0x000110, "Member 'W_Confirmation_C_ExecuteUbergraph_W_Confirmation::CallFunc_GetOwningPlayer_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation, CallFunc_GetOwningPlayer_ReturnValue_4) == 0x000118, "Member 'W_Confirmation_C_ExecuteUbergraph_W_Confirmation::CallFunc_GetOwningPlayer_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation, K2Node_DynamicCast_AsBPI_User_Interface) == 0x000120, "Member 'W_Confirmation_C_ExecuteUbergraph_W_Confirmation::K2Node_DynamicCast_AsBPI_User_Interface' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation, K2Node_DynamicCast_bSuccess) == 0x000130, "Member 'W_Confirmation_C_ExecuteUbergraph_W_Confirmation::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation, CallFunc_GetOwningPlayer_ReturnValue_5) == 0x000138, "Member 'W_Confirmation_C_ExecuteUbergraph_W_Confirmation::CallFunc_GetOwningPlayer_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation, CallFunc_DestroySession_ReturnValue) == 0x000140, "Member 'W_Confirmation_C_ExecuteUbergraph_W_Confirmation::CallFunc_DestroySession_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation, CallFunc_GetOwningPlayer_ReturnValue_6) == 0x000148, "Member 'W_Confirmation_C_ExecuteUbergraph_W_Confirmation::CallFunc_GetOwningPlayer_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation, CallFunc_IsValid_ReturnValue_3) == 0x000150, "Member 'W_Confirmation_C_ExecuteUbergraph_W_Confirmation::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation, K2Node_DynamicCast_AsBPI_User_Interface_1) == 0x000158, "Member 'W_Confirmation_C_ExecuteUbergraph_W_Confirmation::K2Node_DynamicCast_AsBPI_User_Interface_1' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_ExecuteUbergraph_W_Confirmation, K2Node_DynamicCast_bSuccess_1) == 0x000168, "Member 'W_Confirmation_C_ExecuteUbergraph_W_Confirmation::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");

// Function W_Confirmation.W_Confirmation_C.UpdateConfirmation
// 0x0038 (0x0038 - 0x0000)
struct W_Confirmation_C_UpdateConfirmation final
{
public:
	class FText                                   Title;                                             // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FText                                   Message;                                           // 0x0018(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	E_Comfirmation                                ConfirmationFor_0;                                 // 0x0030(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_Confirmation_C_UpdateConfirmation) == 0x000008, "Wrong alignment on W_Confirmation_C_UpdateConfirmation");
static_assert(sizeof(W_Confirmation_C_UpdateConfirmation) == 0x000038, "Wrong size on W_Confirmation_C_UpdateConfirmation");
static_assert(offsetof(W_Confirmation_C_UpdateConfirmation, Title) == 0x000000, "Member 'W_Confirmation_C_UpdateConfirmation::Title' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_UpdateConfirmation, Message) == 0x000018, "Member 'W_Confirmation_C_UpdateConfirmation::Message' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_UpdateConfirmation, ConfirmationFor_0) == 0x000030, "Member 'W_Confirmation_C_UpdateConfirmation::ConfirmationFor_0' has a wrong offset!");

// Function W_Confirmation.W_Confirmation_C.CustomNavigation_Left
// 0x0040 (0x0040 - 0x0000)
struct W_Confirmation_C_CustomNavigation_Left final
{
public:
	EUINavigation                                 Navigation_0;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBPI_UserInterface_C>  K2Node_DynamicCast_AsBPI_User_Interface;           // 0x0010(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBPI_UserInterface_C>  K2Node_DynamicCast_AsBPI_User_Interface_1;         // 0x0028(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(W_Confirmation_C_CustomNavigation_Left) == 0x000008, "Wrong alignment on W_Confirmation_C_CustomNavigation_Left");
static_assert(sizeof(W_Confirmation_C_CustomNavigation_Left) == 0x000040, "Wrong size on W_Confirmation_C_CustomNavigation_Left");
static_assert(offsetof(W_Confirmation_C_CustomNavigation_Left, Navigation_0) == 0x000000, "Member 'W_Confirmation_C_CustomNavigation_Left::Navigation_0' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_CustomNavigation_Left, ReturnValue) == 0x000008, "Member 'W_Confirmation_C_CustomNavigation_Left::ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_CustomNavigation_Left, K2Node_DynamicCast_AsBPI_User_Interface) == 0x000010, "Member 'W_Confirmation_C_CustomNavigation_Left::K2Node_DynamicCast_AsBPI_User_Interface' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_CustomNavigation_Left, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'W_Confirmation_C_CustomNavigation_Left::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_CustomNavigation_Left, K2Node_DynamicCast_AsBPI_User_Interface_1) == 0x000028, "Member 'W_Confirmation_C_CustomNavigation_Left::K2Node_DynamicCast_AsBPI_User_Interface_1' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_CustomNavigation_Left, K2Node_DynamicCast_bSuccess_1) == 0x000038, "Member 'W_Confirmation_C_CustomNavigation_Left::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");

// Function W_Confirmation.W_Confirmation_C.CustomNavigation_Right
// 0x0040 (0x0040 - 0x0000)
struct W_Confirmation_C_CustomNavigation_Right final
{
public:
	EUINavigation                                 Navigation_0;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBPI_UserInterface_C>  K2Node_DynamicCast_AsBPI_User_Interface;           // 0x0010(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBPI_UserInterface_C>  K2Node_DynamicCast_AsBPI_User_Interface_1;         // 0x0028(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(W_Confirmation_C_CustomNavigation_Right) == 0x000008, "Wrong alignment on W_Confirmation_C_CustomNavigation_Right");
static_assert(sizeof(W_Confirmation_C_CustomNavigation_Right) == 0x000040, "Wrong size on W_Confirmation_C_CustomNavigation_Right");
static_assert(offsetof(W_Confirmation_C_CustomNavigation_Right, Navigation_0) == 0x000000, "Member 'W_Confirmation_C_CustomNavigation_Right::Navigation_0' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_CustomNavigation_Right, ReturnValue) == 0x000008, "Member 'W_Confirmation_C_CustomNavigation_Right::ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_CustomNavigation_Right, K2Node_DynamicCast_AsBPI_User_Interface) == 0x000010, "Member 'W_Confirmation_C_CustomNavigation_Right::K2Node_DynamicCast_AsBPI_User_Interface' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_CustomNavigation_Right, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'W_Confirmation_C_CustomNavigation_Right::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_CustomNavigation_Right, K2Node_DynamicCast_AsBPI_User_Interface_1) == 0x000028, "Member 'W_Confirmation_C_CustomNavigation_Right::K2Node_DynamicCast_AsBPI_User_Interface_1' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_CustomNavigation_Right, K2Node_DynamicCast_bSuccess_1) == 0x000038, "Member 'W_Confirmation_C_CustomNavigation_Right::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");

// Function W_Confirmation.W_Confirmation_C.OnPreviewKeyDown
// 0x0388 (0x0388 - 0x0000)
struct W_Confirmation_C_OnPreviewKeyDown final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	struct FKeyEvent                              InKeyEvent;                                        // 0x0038(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm)
	struct FEventReply                            ReturnValue;                                       // 0x0070(0x00B8)(Parm, OutParm, ReturnParm)
	struct FEventReply                            CallFunc_Handled_ReturnValue;                      // 0x0128(0x00B8)()
	struct FEventReply                            CallFunc_OnPreviewKeyDown_ReturnValue;             // 0x01E0(0x00B8)()
	struct FKey                                   CallFunc_GetKey_ReturnValue;                       // 0x0298(0x0018)(HasGetValueTypeHash)
	EUINavigation                                 CallFunc_Key_GetNavigationDirectionFromKey_ReturnValue; // 0x02B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_KeyKey_ReturnValue;            // 0x02B1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x02B2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_KeyKey_ReturnValue_1;          // 0x02B3(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2B4[0x4];                                      // 0x02B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_CustomNavigation_Right_ReturnValue;       // 0x02B8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x02C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2C1[0x7];                                      // 0x02C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_CustomNavigation_Left_ReturnValue;        // 0x02C8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FEventReply                            CallFunc_Handled_ReturnValue_1;                    // 0x02D0(0x00B8)()
};
static_assert(alignof(W_Confirmation_C_OnPreviewKeyDown) == 0x000008, "Wrong alignment on W_Confirmation_C_OnPreviewKeyDown");
static_assert(sizeof(W_Confirmation_C_OnPreviewKeyDown) == 0x000388, "Wrong size on W_Confirmation_C_OnPreviewKeyDown");
static_assert(offsetof(W_Confirmation_C_OnPreviewKeyDown, MyGeometry) == 0x000000, "Member 'W_Confirmation_C_OnPreviewKeyDown::MyGeometry' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_OnPreviewKeyDown, InKeyEvent) == 0x000038, "Member 'W_Confirmation_C_OnPreviewKeyDown::InKeyEvent' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_OnPreviewKeyDown, ReturnValue) == 0x000070, "Member 'W_Confirmation_C_OnPreviewKeyDown::ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_OnPreviewKeyDown, CallFunc_Handled_ReturnValue) == 0x000128, "Member 'W_Confirmation_C_OnPreviewKeyDown::CallFunc_Handled_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_OnPreviewKeyDown, CallFunc_OnPreviewKeyDown_ReturnValue) == 0x0001E0, "Member 'W_Confirmation_C_OnPreviewKeyDown::CallFunc_OnPreviewKeyDown_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_OnPreviewKeyDown, CallFunc_GetKey_ReturnValue) == 0x000298, "Member 'W_Confirmation_C_OnPreviewKeyDown::CallFunc_GetKey_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_OnPreviewKeyDown, CallFunc_Key_GetNavigationDirectionFromKey_ReturnValue) == 0x0002B0, "Member 'W_Confirmation_C_OnPreviewKeyDown::CallFunc_Key_GetNavigationDirectionFromKey_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_OnPreviewKeyDown, CallFunc_EqualEqual_KeyKey_ReturnValue) == 0x0002B1, "Member 'W_Confirmation_C_OnPreviewKeyDown::CallFunc_EqualEqual_KeyKey_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_OnPreviewKeyDown, K2Node_SwitchEnum_CmpSuccess) == 0x0002B2, "Member 'W_Confirmation_C_OnPreviewKeyDown::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_OnPreviewKeyDown, CallFunc_EqualEqual_KeyKey_ReturnValue_1) == 0x0002B3, "Member 'W_Confirmation_C_OnPreviewKeyDown::CallFunc_EqualEqual_KeyKey_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_OnPreviewKeyDown, CallFunc_CustomNavigation_Right_ReturnValue) == 0x0002B8, "Member 'W_Confirmation_C_OnPreviewKeyDown::CallFunc_CustomNavigation_Right_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_OnPreviewKeyDown, CallFunc_BooleanOR_ReturnValue) == 0x0002C0, "Member 'W_Confirmation_C_OnPreviewKeyDown::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_OnPreviewKeyDown, CallFunc_CustomNavigation_Left_ReturnValue) == 0x0002C8, "Member 'W_Confirmation_C_OnPreviewKeyDown::CallFunc_CustomNavigation_Left_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_OnPreviewKeyDown, CallFunc_Handled_ReturnValue_1) == 0x0002D0, "Member 'W_Confirmation_C_OnPreviewKeyDown::CallFunc_Handled_ReturnValue_1' has a wrong offset!");

// Function W_Confirmation.W_Confirmation_C.OnKeyDown
// 0x02C0 (0x02C0 - 0x0000)
struct W_Confirmation_C_OnKeyDown final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	struct FKeyEvent                              InKeyEvent;                                        // 0x0038(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm)
	struct FEventReply                            ReturnValue;                                       // 0x0070(0x00B8)(Parm, OutParm, ReturnParm)
	struct FEventReply                            CallFunc_Handled_ReturnValue;                      // 0x0128(0x00B8)()
	struct FKey                                   CallFunc_GetKey_ReturnValue;                       // 0x01E0(0x0018)(HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_KeyKey_ReturnValue;            // 0x01F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_KeyKey_ReturnValue_1;          // 0x01F9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1FA[0x6];                                      // 0x01FA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FEventReply                            CallFunc_Unhandled_ReturnValue;                    // 0x0200(0x00B8)()
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x02B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(W_Confirmation_C_OnKeyDown) == 0x000008, "Wrong alignment on W_Confirmation_C_OnKeyDown");
static_assert(sizeof(W_Confirmation_C_OnKeyDown) == 0x0002C0, "Wrong size on W_Confirmation_C_OnKeyDown");
static_assert(offsetof(W_Confirmation_C_OnKeyDown, MyGeometry) == 0x000000, "Member 'W_Confirmation_C_OnKeyDown::MyGeometry' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_OnKeyDown, InKeyEvent) == 0x000038, "Member 'W_Confirmation_C_OnKeyDown::InKeyEvent' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_OnKeyDown, ReturnValue) == 0x000070, "Member 'W_Confirmation_C_OnKeyDown::ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_OnKeyDown, CallFunc_Handled_ReturnValue) == 0x000128, "Member 'W_Confirmation_C_OnKeyDown::CallFunc_Handled_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_OnKeyDown, CallFunc_GetKey_ReturnValue) == 0x0001E0, "Member 'W_Confirmation_C_OnKeyDown::CallFunc_GetKey_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_OnKeyDown, CallFunc_EqualEqual_KeyKey_ReturnValue) == 0x0001F8, "Member 'W_Confirmation_C_OnKeyDown::CallFunc_EqualEqual_KeyKey_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_OnKeyDown, CallFunc_EqualEqual_KeyKey_ReturnValue_1) == 0x0001F9, "Member 'W_Confirmation_C_OnKeyDown::CallFunc_EqualEqual_KeyKey_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_OnKeyDown, CallFunc_Unhandled_ReturnValue) == 0x000200, "Member 'W_Confirmation_C_OnKeyDown::CallFunc_Unhandled_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Confirmation_C_OnKeyDown, CallFunc_BooleanOR_ReturnValue) == 0x0002B8, "Member 'W_Confirmation_C_OnKeyDown::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");

}

