#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Input_Icon

#include "Basic.hpp"

#include "W_Input_Icon_classes.hpp"
#include "W_Input_Icon_parameters.hpp"


namespace SDK
{

// Function W_Input_Icon.W_Input_Icon_C.ExecuteUbergraph_W_Input_Icon
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Input_Icon_C::ExecuteUbergraph_W_Input_Icon(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Input_Icon_C", "ExecuteUbergraph_W_Input_Icon");

	Params::W_Input_Icon_C_ExecuteUbergraph_W_Input_Icon Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Input_Icon.W_Input_Icon_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UW_Input_Icon_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Input_Icon_C", "PreConstruct");

	Params::W_Input_Icon_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Input_Icon.W_Input_Icon_C.OnInputDeviceChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// EFancyInputDevice                       NewInputDevice                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Input_Icon_C::OnInputDeviceChanged(EFancyInputDevice NewInputDevice)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Input_Icon_C", "OnInputDeviceChanged");

	Params::W_Input_Icon_C_OnInputDeviceChanged Parms{};

	Parms.NewInputDevice = NewInputDevice;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Input_Icon.W_Input_Icon_C.UpdateIcon
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EFancyInputDevice                       InputDevice                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Show                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UW_Input_Icon_C::UpdateIcon(EFancyInputDevice InputDevice, bool Show)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Input_Icon_C", "UpdateIcon");

	Params::W_Input_Icon_C_UpdateIcon Parms{};

	Parms.InputDevice = InputDevice;
	Parms.Show = Show;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Input_Icon.W_Input_Icon_C.OnLoaded_ED0A6EA547ADA5E1277085BE13103EF7
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Input_Icon_C::OnLoaded_ED0A6EA547ADA5E1277085BE13103EF7(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Input_Icon_C", "OnLoaded_ED0A6EA547ADA5E1277085BE13103EF7");

	Params::W_Input_Icon_C_OnLoaded_ED0A6EA547ADA5E1277085BE13103EF7 Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}

}

