#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_OptionSwitcher_Theme2

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Backrooms_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WB_OptionSwitcher_Theme2.WB_OptionSwitcher_Theme2_C
// 0x0050 (0x02B0 - 0x0260)
class UWB_OptionSwitcher_Theme2_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UButton*                                Decrease_Btn;                                      // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                FocusBackground;                                   // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Increase_Btn;                                      // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock;                                         // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(int32 SelectedOption)> OnOptionSwitched;                           // 0x0288(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TArray<class FText>                           Options;                                           // 0x0298(0x0010)(Edit, BlueprintVisible)
	int32                                         SelectedOption;                                    // 0x02A8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Allow_OptionLooping_;                              // 0x02AC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_WB_OptionSwitcher_Theme2(int32 EntryPoint);
	void ToggleFocus(bool IsFocused);
	void BndEvt__WB_OptionSwitcher_Increase_Btn_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_OptionSwitcher_Decrease_Btn_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void Construct();
	void PreConstruct(bool IsDesignTime);
	void ToggleEnabled(bool IsEnabled);
	void ToggleHover(bool IsHovered_0);
	void Switch_Option(bool Decrease_);
	void Set_SelectedOption(const class FText& SelectedOption_0);
	void Setup();
	struct FEventReply OnKeyDown(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WB_OptionSwitcher_Theme2_C">();
	}
	static class UWB_OptionSwitcher_Theme2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_OptionSwitcher_Theme2_C>();
	}
};
static_assert(alignof(UWB_OptionSwitcher_Theme2_C) == 0x000008, "Wrong alignment on UWB_OptionSwitcher_Theme2_C");
static_assert(sizeof(UWB_OptionSwitcher_Theme2_C) == 0x0002B0, "Wrong size on UWB_OptionSwitcher_Theme2_C");
static_assert(offsetof(UWB_OptionSwitcher_Theme2_C, UberGraphFrame) == 0x000260, "Member 'UWB_OptionSwitcher_Theme2_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWB_OptionSwitcher_Theme2_C, Decrease_Btn) == 0x000268, "Member 'UWB_OptionSwitcher_Theme2_C::Decrease_Btn' has a wrong offset!");
static_assert(offsetof(UWB_OptionSwitcher_Theme2_C, FocusBackground) == 0x000270, "Member 'UWB_OptionSwitcher_Theme2_C::FocusBackground' has a wrong offset!");
static_assert(offsetof(UWB_OptionSwitcher_Theme2_C, Increase_Btn) == 0x000278, "Member 'UWB_OptionSwitcher_Theme2_C::Increase_Btn' has a wrong offset!");
static_assert(offsetof(UWB_OptionSwitcher_Theme2_C, TextBlock) == 0x000280, "Member 'UWB_OptionSwitcher_Theme2_C::TextBlock' has a wrong offset!");
static_assert(offsetof(UWB_OptionSwitcher_Theme2_C, OnOptionSwitched) == 0x000288, "Member 'UWB_OptionSwitcher_Theme2_C::OnOptionSwitched' has a wrong offset!");
static_assert(offsetof(UWB_OptionSwitcher_Theme2_C, Options) == 0x000298, "Member 'UWB_OptionSwitcher_Theme2_C::Options' has a wrong offset!");
static_assert(offsetof(UWB_OptionSwitcher_Theme2_C, SelectedOption) == 0x0002A8, "Member 'UWB_OptionSwitcher_Theme2_C::SelectedOption' has a wrong offset!");
static_assert(offsetof(UWB_OptionSwitcher_Theme2_C, Allow_OptionLooping_) == 0x0002AC, "Member 'UWB_OptionSwitcher_Theme2_C::Allow_OptionLooping_' has a wrong offset!");

}

